// Mapeamento de nomes de Material Symbols para Lucide Icons
export const iconMap: Record<string, string> = {
  // Navegação
  'expand_more': 'ChevronDown',
  'expand_less': 'ChevronUp',
  'home': 'Home',
  'folder': 'Folder',
  'person': 'User',
  'logout': 'LogOut',
  'info': 'Info',
  'settings': 'Settings',
  'close': 'X',
  'menu': 'Menu',
  
  // Ações
  'add': 'Plus',
  'add_circle': 'PlusCircle',
  'delete': 'Trash2',
  'edit': 'Edit',
  'upload': 'Upload',
  'download': 'Download',
  'save': 'Save',
  'check': 'Check',
  'check_circle': 'CheckCircle',
  'cancel': 'X',
  'search': 'Search',
  'filter_list': 'Filter',
  
  // Notificações e Status
  'notifications': 'Bell',
  'notifications_off': 'BellOff',
  'bolt': 'Zap',
  'lightbulb': 'Lightbulb',
  'auto_awesome': 'Sparkles',
  'auto_fix_high': 'Wand2',
  'auto_fix': 'Wand2',
  
  // Mídia
  'image': 'Image',
  'imagesmode': 'Images',
  'collections': 'ImageIcon',
  'photo_library': 'ImageIcon',
  'movie': 'Film',
  'videocam': 'Video',
  'play_circle': 'PlayCircle',
  'play_arrow': 'Play',
  'volume_up': 'Volume2',
  'fullscreen': 'Maximize',
  
  // Design e Layout
  'grid_view': 'Grid3x3',
  'grid_on': 'Grid3x3',
  'list': 'List',
  'layers': 'Layers',
  'rectangle': 'RectangleHorizontal',
  'square': 'Square',
  'crop_square': 'Square',
  'circle': 'Circle',
  'title': 'Type',
  'text_fields': 'Type',
  'gradient': 'Gradient',
  'palette': 'Palette',
  'brush': 'Paintbrush',
  'crop': 'Crop',
  'flip': 'FlipHorizontal',
  'filter_vintage': 'Filter',
  
  // Social e Comunicação
  'share': 'Share2',
  'language': 'Languages',
  'alternate_email': 'AtSign',
  'attach_file': 'Paperclip',
  'attachment': 'Paperclip',
  'send': 'Send',
  'north': 'ArrowUp',
  'south': 'ArrowDown',
  'east': 'ArrowRight',
  'west': 'ArrowLeft',
  'arrow_upward': 'ArrowUp',
  'arrow_downward': 'ArrowDown',
  'arrow_forward': 'ArrowRight',
  'arrow_back': 'ArrowLeft',
  'chat_bubble_outline': 'MessageCircle',
  'chat_bubble': 'MessageCircle',
  'chat': 'MessageSquare',
  'key': 'Key',
  'open_in_new': 'ExternalLink',
  'error': 'AlertCircle',
  'error_outline': 'AlertCircle',
  'warning': 'AlertTriangle',
  'help': 'HelpCircle',
  'help_outline': 'HelpCircle',
  
  // Visualização
  'visibility': 'Eye',
  'visibility_off': 'EyeOff',
  'lock': 'Lock',
  'lock_open': 'Unlock',
  'lock_closed': 'Lock',
  
  // Outros
  'cloud_upload': 'CloudUpload',
  'dashboard': 'LayoutDashboard',
  'waving_hand': 'Hand',
  'shopping_bag': 'ShoppingBag',
  'smart_toy': 'Bot',
  'rocket_launch': 'Rocket',
  'aspect_ratio': 'AspectRatio',
  'refresh': 'RefreshCw',
  'remove': 'Minus',
  'add_box': 'PlusSquare',
  'near_me': 'Move',
  'settings_suggest': 'Settings2',
  'tune': 'SlidersHorizontal',
  'view_in_ar': 'Box',
  'favorite': 'Heart',
  'star': 'Star',
  'check_circle_outline': 'CheckCircle2',
  'add_circle_outline': 'PlusCircle',
  'dark_mode': 'Moon',
  'light_mode': 'Sun',
  'brand_family': 'Users',
  'category': 'Tags',
  'ink_eraser': 'Eraser',
  'magic_button': 'Wand2',
  'tips_and_updates': 'Lightbulb',
  'unfold_more': 'ChevronsUpDown',
  'format_align_left': 'AlignLeft',
  'format_align_center': 'AlignCenter',
  'format_align_right': 'AlignRight',
  'format_strikethrough': 'Strikethrough',
  'photo_camera': 'Camera',
  'business': 'Building2',
  'social_leaderboard': 'TrendingUp',
  'hd': 'Maximize',
  'variations': 'Copy',
  'portrait': 'User',
  'add_photo_alternate': 'ImagePlus',
  'rotate_right': 'RotateCw',
  'north_west': 'ArrowUpLeft',
  'north_east': 'ArrowUpRight',
  'south_west': 'ArrowDownLeft',
  'south_east': 'ArrowDownRight',
  'align_horizontal_center': 'Minus',
  'align_vertical_center': 'Minus',
  'center_focus_strong': 'Focus',
  'crosshair': 'Focus',
  
  // Navegação de mídia
  'chevron_left': 'ChevronLeft',
  'chevron_right': 'ChevronRight',
  'navigate_before': 'ChevronLeft',
  'navigate_next': 'ChevronRight',
  'skip_previous': 'SkipBack',
  'skip_next': 'SkipForward',
  
  // Carrossel e Redes Sociais
  'view_carousel': 'GalleryHorizontal',
  'slideshow': 'Presentation',
  'work': 'Briefcase',
  'content_copy': 'Copy',
  'crop_portrait': 'Smartphone',
  'crop_landscape': 'Monitor',
  'hexagon': 'Hexagon',
}
